# Shell variables
# Generated by 'wal'
wallpaper='/home/zlin/Pictures/wallpapers/cyber.png'

# Special
background='#0C0D0D'
foreground='#d8dad5'
cursor='#d8dad5'

# Colors
color0='#0C0D0D'
color1='#5E606A'
color2='#C6B458'
color3='#5F619C'
color4='#956C81'
color5='#4EB5BE'
color6='#9E9D9F'
color7='#d8dad5'
color8='#979895'
color9='#5E606A'
color10='#C6B458'
color11='#5F619C'
color12='#956C81'
color13='#4EB5BE'
color14='#9E9D9F'
color15='#d8dad5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
