## Colors configuration
colors:
  # Default colors
  primary:
    background: '#090708'
    foreground: '#cecdd1'

  # Normal colors
  normal:
    black:   '#090708'
    red:     '#605B66'
    green:   '#676371'
    yellow:  '#953E42'
    blue:    '#A24C50'
    magenta: '#EA5155'
    cyan:    '#837D84'
    white:   '#cecdd1'

  # Bright colors
  bright:
    black:   '#171215'
    red:     '#6d6773'
    green:   '#736f7f'
    yellow:  '#a7464a'
    blue:    '#b0575c'
    magenta: '#ed686c'
    cyan:    '#8f8a90'
    white:   '#dbdadd'
