# Shell variables
# Generated by 'wal'
wallpaper='/home/zlin/Pictures/wallpapers/desert.jpg'

# Special
background='#0d0905'
foreground='#d4cec9'
cursor='#d4cec9'

# Colors
color0='#0d0905'
color1='#746047'
color2='#946A4B'
color3='#B38F6D'
color4='#C3A17B'
color5='#697990'
color6='#758294'
color7='#d4cec9'
color8='#94908c'
color9='#746047'
color10='#946A4B'
color11='#B38F6D'
color12='#C3A17B'
color13='#697990'
color14='#758294'
color15='#d4cec9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
