# Shell variables
# Generated by 'wal'
wallpaper='/home/zlin/.config/wpg/wallpapers/pink-mecha.png'

# Special
background='#21252e'
foreground='#d1cadb'
cursor='#d1cadb'

# Colors
color0='#21252e'
color1='#93729A'
color2='#A06D99'
color3='#887CA2'
color4='#958BAD'
color5='#A294B6'
color6='#AC9EC1'
color7='#d1cadb'
color8='#928d99'
color9='#93729A'
color10='#A06D99'
color11='#887CA2'
color12='#958BAD'
color13='#A294B6'
color14='#AC9EC1'
color15='#d1cadb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

accent=$color12
light_value='0.05'
dark_value='0.30'

# Wallpaper
#wdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#wallpaper="$wdir/wallpaper"

# Polybar
polybar_font='Iosevka Nerd Font:size=10;3'

# Rofi
rofi_font='Iosevka 10'
rofi_icon='flattrcolor'

# Terminal
terminal_font_name='JetBrainsMono Nerd Font'
terminal_font_size='10'

# Geany
geany_colors='wal.conf'
geany_font='JetBrains Mono 10'

# Appearance
gtk_font='Noto Sans 9'
gtk_theme='FlatColor'
icon_theme='flattrcolor'
cursor_theme='Qogirr-Dark'

# Dunst
dunst_width='300'
dunst_height='80'
dunst_offset='10x42'
dunst_origin='top-right'
dunst_font='Iosevka Custom 9'
dunst_border='1'
dunst_separator='1'

# Picom
picom_backend='glx'
picom_corner='0'
picom_shadow_r='14'
picom_shadow_o='0.30'
picom_shadow_x='-12'
picom_shadow_y='-12'
picom_blur_method='none'
picom_blur_strength='0'

# Bspwm
bspwm_fbc="$accent"
bspwm_nbc="$background"
bspwm_abc="$color5"
bspwm_pfc="$color2"
bspwm_border='1'
bspwm_gap='10'
bspwm_sratio='0.50'

# Don't Delete This File
